window.POEMS = [
    {
        "id":  "poem-anger",
        "title":  "Anger",
        "text":  "I used to apologize for it before it even arrived, Pre emptive sorry, shrinking before I was even asked to shrink. Swallowing things that deserved to be said out loud and calling that maturity when it was mostly fear.\n\nAnger isn\u0027t the problem, What you do with it is, and I\u0027ve done both. I\u0027ve burned things I shouldn\u0027t have, and I\u0027ve buried things that deserved a fire, neither one worked, both just left damage.\n\nI\u0027m finding the middle version, the anger that speaks clearly, not from a wound, not to wound, but to mark a line. This is where I stop. This is what I won\u0027t accept. I say it once, calmly, with both feet on the ground.\n\nThat\u0027s not aggression. That\u0027s dignity. That\u0027s knowing what matters enough to protect with your voice. I stopped apologizing for the fact that I feel things. Turns out the feeling was never the problem, the hiding was. You don\u0027t have to be quiet to be good.\n\n#60\nAlvin \n"
    },
    {
        "id":  "poem-anxiety",
        "title":  "Anxiety",
        "text":  "It starts before I have a reason to give it, \nA heartbeat.. A strong sense that something, something is about to go wrong in a way I can\u0027t prepare for.. but should probably be preparing for right now.\n\nMy brain runs worst case  scenarios like a simulation, \nNot once.. repeatedly, with small variations, very detailed, \nBy the time the event arrives I\u0027ve already survived six versions of disaster\nand I\u0027m exhausted from a fight that never happened.\n\nThe real events are almost always lighter than the previews. I walk in, it goes fine, I walk out, I breathe. And I think.. all that for this. And I almost laugh. And then the next thing starts loading. \n\nI\u0027m learning to name it without feeding it. This is anxiety. This is not information. This is noise. I\u0027m learning to let the heartbeat be there without controlling it. It\u0027s slow work, but I\u0027m somewhere in the middle of it. \n\n\n"
    },
    {
        "id":  "poem-at-least",
        "title":  "At least",
        "text":  "I, \nshowed up.\nThat\u0027s more than most people do and less than it mattered. Said the right things to the same person just in a costume. \n\nI, \nHeld the door open long enough to know, nobody was coming through.\nSome efforts don\u0027t deserve applause, just a little acknowledgement \n\nI, \ntried, The universe noted it.\nWe\u0027ve both moved on.\n\nAt Least\nI showed up with good intentions, that\u0027s more than most people do and less than it mattered in the end. Said all the right things to the wrong version. \n\nbut I held it anyway, because that\u0027s just me.\nSome efforts don\u0027t deserve applause —\njust a quiet nod from yourself\nsomewhere on the drive home.\nI tried. The universe noted it.\nWe\u0027ve both moved on, apparently.\nAnd honestly — I\u0027ll probably still care\nwhen I shouldn\u0027t, longer than I should,\nin that embarrassing way that says less about you\nand everything about the kind of person I am.\nCould be worse.\n"
    },
    {
        "id":  "poem-becoming-myself",
        "title":  "Becoming myself",
        "text":  "You left long before you walked away,\u000b \nyet I kept reaching,\nhoping your shadow would finally turn into a father.\n\nYour stories broke open in time,\u000b \ntruths hidden under all the lies,\npain stitched behind every memory.\n\nBut somewhere between the anger\n\u000band the empty promises,\u000b\n I found something real, me.\n\nNot the boy waiting for you to return,\u000b \nbut the man learning to stand\nWithout the weight of your absence.\n\nMom carried the house,\u000b I carried the hurt,\n\u000byet here I am,\u000b still rising, \nstill choosing\u000b a heart that doesn’t harden.\n\nYour disappearance didn’t end me.\u000b\nIt revealed me, and the ruins you left behind,\nMade me meet the person I was always meant to become.\n\n#pure royalty\nALvin\n\n"
    },
    {
        "id":  "poem-beyond-the-physical-rush",
        "title":  "Beyond the physical rush",
        "text":  "We move too fast sometimes\nCalling it vibes or chemistry\u000b \nSkipping the part where we actually talk\nThinking closeness means touch\u000b\n When it really means feeling safe. \n\nNobody owes access to their body\u000b \nStaying should be a choice\u000b \nNot pressure, not expectations\u000b \nJust mutual interest\u000band clear respect\n\nReal love isn’t rushed\u000b \nIt listens more than it pushes\u000b\n It’s okay with slowing down\u000b \nWith hearing No, And still showing care\n\nAlvin. #protectyourpeace\n\n\n"
    },
    {
        "id":  "poem-ephemeral",
        "title":  "Ephemeral",
        "text":  "She\u0027s somewhere between real and almost \nclose enough to feel,\nfar enough to question.\nI keep finding her in small things,\nwhich is either a sign\nor just what hoping looks like from the inside.\nWarm one moment, distant the next \nLike the sun, except she decides when to rise \nthat could mean anything, \nright? \nI\u0027ve been solving for x\nBut she\u0027s part of the equation too, \nCause she keeps changing the value of y \nSo i just play along. \nStill, I come back.\nNot because i found a way through, no\nThe most interesting systems\ndon\u0027t let you in easily \nbut because uncertain feels like the most alive I\u0027ve been\nI smile either way\nEither way I\u0027m here \nwhich is its own kind of answer.\n\nAlvin\n"
    },
    {
        "id":  "poem-exit",
        "title":  "Exit",
        "text":  "People who leave that way don\u0027t escape the pain\nthey just stop being able to find out they were wrong \nThere is no dramatic silence after\nNo watching people cry at your grave\nand feeling seen at last.\nCalls itself a gift \nBut gifts don\u0027t leave people \nJust gone. Just nothing\nAnd somewhere a mother\nopens a bedroom door\nand the world \nsplits in two forever.\nSuicide doesn\u0027t end suffering.\nIt sells you silence \nLike silence is the same as peace\nLike the noise inside your head \nis proof the world won\u0027t grieve. \nThe cruelest part \nmost people who survive it\nsay they didn\u0027t want to die\nThey just wanted the hurting to stop\nThose are two different things\none of them survives\n\nAlvin\n\n\n"
    },
    {
        "id":  "poem-found",
        "title":  "Found",
        "text":  "She left for school but never came back, \nThe news said \"found\" like she had just losther way, \nWe told her to be careful, just in case,\nBeside the road her was life erased.\n\nThey stick her picture on the walls and walk away, \nWe scroll past her between a meme and our stories \nWe hand out \"stay safe\" to girls like it\u0027s advice,\nSo sad we\u0027ve normalized what we ignore.\n\nHer books has tomorrow\u0027s homework in it,\nDidn\u0027t she deserve to fill each empty page? \nWe mourn for a week and we call it closure \nThen wonder why we mourn one girl more. \n\nWe get mad, we share, we cry, \nThen switch to some thing lighter \nElection season, her name is used as leverage. \nWe speak, march, demand, what else can we do? \nbecause our silence is their biggest wage\nCause every time we\u0027re quiet, they grow bolder. \n\nAlvin\n"
    },
    {
        "id":  "poem-growing-up",
        "title":  "Growing up",
        "text":  "Nobody told me it would happen this quietly,\nno ceremony, no moment where the music swells.\nJust one morning you\u0027re tying your shoes and you realize\nyour hands look like your father\u0027s and that\u0027s that.\n\nYou stop asking for permission and start asking for forgiveness, you stop saying someday and start checking your calendar. The things you thought were boring become routine, and the things you thought were forever become memories.\n\nI miss the version of me that had no concept of time,\nwho played until it got dark and came home hungry.\nNow I track my hours like a man on a deadline,\nbecause I am, we all are, we just don\u0027t say it out loud.\n\nGrowing up isn\u0027t losing your childhood, exactly.\nIt\u0027s more like carrying it behind you, getting heavier each year.\nBut you don\u0027t put it down. You keep walking.\nThat weight is proof you had something worth remembering.. The reasons why all thats lost isn\u0027t actually gone but just out of reach \n\nAlvin"
    },
    {
        "id":  "poem-hear-me",
        "title":  "Hear me",
        "text":  "One says go, the other says stay,\none whispers you\u0027re enough, the other screams you\u0027re not, \nI\u0027m being pulled in two directions, losing my way,\nbut somewhere in the middle, I\u0027m tearing apart.\nThey\u0027re both so loud I can\u0027t hear myself, \nshould I think or should I pray?\n\nMy heart wants one thing, the world wants another,\none voice says chase your dreams, the other says survive first, \nThey\u0027re killing each other inside my head,\ncaught between two truths I can\u0027t both hold.\nSo which one do I choose when they\u0027re both screaming?\n\nI\u0027m paralyzed by the conflict, can\u0027t break free,\nstuck between what I love and what\u0027s safe,\nbetween who I want to be and who they need me to be, \nBoth voices claim they\u0027re trying to save me,\nbut they\u0027re both drowning me at the same time.\n\nSo maybe the real problem isn\u0027t choosing,\nmaybe I\u0027ve been listening so hard I forgot I had a voice.\nAnd the scariest part? \nI don\u0027t know if my voice would sound any different,\nor if I\u0027ve become them entirely.\n\n#57\nAlvin \n"
    },
    {
        "id":  "poem-heartbeat",
        "title":  "Heartbeat",
        "text":  "I felt my chest go still, no beat, no race,\njust silence where there used to be a song.\nI  felt so cold, so out of place\nReminding myself that I\u0027m still strong \nBut nooo! all I felt was tired, done\nRhythm of my life being slowly undone\n\nNo breathe i could take, no sound i could hear, \nJudgement was done in that very moment \ndying is a fearful thing\nno pain, no fight, no desperate, wild cling\nThis time i was gone yet somehow still I\u0027m here\nIt was a dream, i relieved my fear \n\nLying there in darkness, i smiled\nI\u0027m alive! My eyes flew open black\nthat dream was just a preview of what i left back\nJust a dream, just shadows, it all passed\nBut in my chest, that racing beat won\u0027t slow\nit\u0027s counting down the heartbeats left I owe\n\n\nEp 49\nAlvin\n"
    },
    {
        "id":  "poem-identity",
        "title":  "IDENTITY",
        "text":  "I have performed so many versions of myself\nthat some days I can\u0027t find the original.\nThe one that existed before the world had opinions\nbefore I learned to adjust based on the room in general. \nI code-switch, shape-shift, edit in real time.\nHave this version for home, That one for outside.\nAnother for people who need me to be smaller.\nAnother for places where small feels like survival.\nIt\u0027s exhausting. Not in a dramatic way, just steady,\nthe way carrying a bag all day tires your shoulder.\nBut you still need to,\nYou don\u0027t notice until you put it down.\nI\u0027m still learning how to put it down.\nSomewhere underneath all the adjustments is someone real.\nSomeone who laughs too loud and takes up space unapologetically.\nI\u0027m not there yet. But I\u0027m moving towards it.\nOr at least I think I am\nValidating my self daily is not the way i want it.\n\nAlvin\n\n\n\n\n\n\n\n\n"
    },
    {
        "id":  "poem-its-an-illusion",
        "title":  "Its an illusion",
        "text":  "I did not love you in illusion; I loved you with awareness and care,.. Slowly watching who you became when comfort disappeared and honesty filled the air,.. some point doubted if you were really there.\n\nMachiavelli once said  that hearts move where advantage is found, and so I listened between the lines,\nin the quiet, in the distance,  the choices that appeared when the beauty met resistance i mean..\n\nI chose clarity over fantasy, ..Patience over desire’s command, chose her because she wasn\u0027t in demand,because love becomes devotion only when intention walks hand-in-hand with discipline’s quiet stand... \n\nHe warned that power built on fear dissolves, while respect remains and grows,\nso I guided my motions... like a watchman at night, restrained at my words that might dive at my emotions ... aware that longing with wisdom aside can build a dream only to let it fracture and divide...\n\nI chased love to escape myself, not to find another.. But do we really need another? Our desire for love grows stronger in absence than in presence..so.. We should just stay aware, stay prepared, stay woke and learn to own mistakes instead of blaming fate,, maybe just, maybe we\u0027ll realise we want the truth only when lies no longer benefits us.\n\nAlviin✌️\n\nEP 30\n\n\n"
    },
    {
        "id":  "poem-m-i-a",
        "title":  "M_ I_ A",
        "text":  "You decided to leave early \nYet still I reached out daily \nThe lies about mom you fed me\nExposed were truths I didn\u0027t see\nSang, \u0027We\u0027ll buy a car one day\u0027\nFound out you couldn\u0027t drive any\n\n\nInheritance was always on my mind \nYet Countryside you had no land\nTold me work hard my boy\nSeeing you in school gives me joy \nMom was the breadwinner all this time\nYet you treated her like she did a crime\n   \n\nDisappointed is an actual understatement\nFor all the beating and resentment\nShe tolerated you for a reason \nHoping one day YOU would reason \nQuietly she showered you with praises\nBut all you did was teach us to do our laces\n\nMemories of you slowly went dim\nTunnel\u0027s ends had only but a beam\nTried to kill us for self benefit\nAll our friends knew the news didn\u0027t fit \nLived a life full of destruction\nTen years and your still Missing In Action \n\nI was 19 when u finally came around\nDisregarding everyone i held to surround \nNever took you for a coward until then\nMaybe i did , your an embarrassment to men\nYou gave me promises filled with pleasure\nTalking about you makes me  have pressure \n\nAlvin✌\n"
    },
    {
        "id":  "poem-nostalgia",
        "title":  "Nostalgia",
        "text":  "I went back to a place I grew up loving, \nand it looked smaller than I remembered.\nNot worse — just smaller. More ordinary.\nThe magic was in me, not the place, and I\u0027d moved it without knowing.\n\nMemory does that. It upgrades everything slightly.\nSofter light, warmer air, everyone kinder.\nA past so edited you can\u0027t live in it anymore,\nonly visit, and even then, it\u0027s not quite right.\n\nI miss things that may not have been exactly as I miss them.\nThat\u0027s the honest version. The nostalgia is real\nbut the thing it\u0027s pointing to might be as much invention as memory.\nI\u0027ve mourned places that never quite existed.\n\nStill, I don\u0027t think that makes it worthless.\nThe feeling is real, even if the picture isn\u0027t perfect.\nAnd the person I was in those moments uncertain, young, alive\ndeserves to be remembered fondly, even if I\u0027ve moved on.\n\nAlvin\n\n"
    },
    {
        "id":  "poem-reverie",
        "title":  "Reverie",
        "text":  "She exists in the spaces between my thoughts,\nor maybe I exist in hers,\nBut here\u0027s the magic of it all,, \nshe is the quiet I\u0027ve been chasing,\nthe acceptance without the asking.\n\nI want her like I want to breathe,\nbut maybe I\u0027m just dreaming oxygen.\nShe feels like peace, tastes like a question mark,\nand I\u0027m playfully drowning in the answer.\n\nSo I\u0027m drowning deeper, and I don\u0027t want to surface.\nShe\u0027s everywhere now,, in the way I think,\nthe way I move, the spaces between my heartbeats.\nI\u0027m so in love it\u0027s become a religion, \na madness, a beautiful sickness I won\u0027t cure.\n\nEvery moment without her is borrowed time, \nevery moment with her is eternity.\nShe\u0027s real enough to destroy me, dream enough to save me,\nand I\u0027m holding on like she\u0027s the only thing keeping me alive\nbecause she is.\n\nAnd I don\u0027t need to know if she\u0027s real anymore,\nbecause this.. this ache, this want, this peace... \nfeels more real than breathing.\nI\u0027ve stopped questioning the line, \nbetween fantasy and truth.\n\nSo let me stay here, suspended in this feeling,\nin the glow of her acceptance, \nin the madness of my own devotion.\nThis is all I need to be, \nlost in a reverie ❤️\n\n#55\nAlvin\n"
    },
    {
        "id":  "poem-the-cruel-kind-of-kind",
        "title":  "The Cruel kind of kind_",
        "text":  "We were just talking, nothing serious,\nLate nights, dry jokes, you being mysterious.\nYou\u0027d send a meme, I\u0027d send one back,\nEasy conversation, no pressure, maybe i was in luck. \n\nYou started leaving hearts on random things I said,\nI didn\u0027t read too much into it, kept a cool head.\nThen the texts got longer, warmer, a little more,\nStarted feeling like something I\u0027d felt before.\n\nYou\u0027d say \"I miss this\" and I\u0027d say i feel the same, \nNeither of us putting a name to the game.\nThen you went quiet, back to your life, I suppose \nYou already won, why\u0027d you come back just to watch me lose?\n\nAlvin\n"
    },
    {
        "id":  "poem-what-if-ii",
        "title":  "What if  II",
        "text":  "What if you just stopped asking what if, \nWhat if the mirror cracked and didn\u0027t buy a new one,\nBelieving a reflection that you are the broken one, \nWhat if \"less\" was enough because it was yours, \nNot borrowed from someone\u0027s highlight reel,\nGenuine cause they don\u0027t need to see what\u0027s real. \n\nWhat if you just existed without needing proof, \nWhat if peace was something you achieve without approval, \nPerforming daily just to get rid of denial, \nWhat if the insecurity was never your fault, \nImaginary comment feeding you with guilt. \n\nWhat if you opened up instead of posting about it, \nWhat if you actually said what you meant, \nand people stuck around for it, loved you because of it,stayed because of it, \nWhat if the drowning in your thoughts was necessary,\nRevisiting every memory that was buried. \n\nWhat if tomorrow you just didn\u0027t check,\ndidn\u0027t scroll, didn\u0027t compare, didn\u0027t wait for the notification,\nWhat if you texted someone you actually miss, \nThe one you chose silence over just to dismiss \nWhat if it\u0027s not in this life, not today,\nMaybe tomorrow, maybe another life you\u0027ll stay.\n\n\nEp 41\nAlvin\n\n"
    },
    {
        "id":  "poem-what-if",
        "title":  "What if",
        "text":  "What if the mirror’s just lying again,\ncalling you “less” like it knows your name, \nWhat if the flaw was never your frame,\njust old voices playing a tired game,\nand you were enough before your doubt ever came, \n\nWhat if the weight was never on your skin,\nUsing  filters and angles, posing as thin,\nMaking you question your size over and over again,\nCounting every \u0027loss\u0027 as a gain,\nDoubting your self, waiting on likes just to feel okay again, \n\nWhat if those lives you see on your screen,\nHide the parts where the hurts are seen,\nAll the lavish you wish you had been in,\nbattle you know you cant win, by playing clean,\nand you\u0027ve been comparing your truth to a scene,\n\nWhat if you’re tired of trying to fit in, play pretend,\nlaughing  louder just to make new friends,\ngood days turn grey from a text left on \u0027seen\u0027, \nReading too deep the words in between,\nchasing their praise like it pays something due,\nlose your own voice tryna sound more approved, \n\nWhat if the peace you want isn’t earned,\nnot in their words or the way they confirm,\nnot in applause or the tables that turn,\nmaybe self-worth isn’t something you learn, \nmaybe it’s yours, something steady, something sure, \nwhat if?\n\nAlvin"
    }
];
